spring:
  application:
    name: Only-Admin
  datasource:
    url: jdbc:mysql://localhost:3306/only_admin
    username: root
    password: R@mySql@0900
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    url: jdbc:mysql://localhost:3306
    schemas: only_admin
    user: root
    password: R@mySql@0900

  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 100
        order_updates: true
        order_inserts: true
