spring:
  application:
    name: Only-Admin
  datasource:
    url: jdbc:mysql://localhost:3306/only_admin
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    url: ${JDBC_URL:jdbc:mysql://localhost:3306}
    schemas: ${DB:only_admin}
    user: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:admin}

  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 100
        order_updates: true
        order_inserts: true
